export enum AuditLogAction {
  USER_LOGIN = 'USER_LOGIN',
  USER_LOGOUT = 'USER_LOGOUT',
  CONTENT_CREATED = 'CONTENT_CREATED',
  CONTENT_UPDATED = 'CONTENT_UPDATED',
  CONTENT_STATUS_CHANGED = 'CONTENT_STATUS_CHANGED',
  USER_ROLE_CHANGED = 'USER_ROLE_CHANGED',
  USER_CREATED = 'USER_CREATED', // Kept for backwards compatibility, but invite is preferred
  USER_INVITED = 'USER_INVITED',
  USER_REGISTERED = 'USER_REGISTERED',
  PASSWORD_RESET_REQUESTED = 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET_COMPLETED = 'PASSWORD_RESET_COMPLETED',
  CONTENT_DELETED = 'CONTENT_DELETED',
  CONTENT_SCHEDULED = 'CONTENT_SCHEDULED',
  CONTENT_RESTORED = 'CONTENT_RESTORED',
  CONTENT_PERMANENTLY_DELETED = 'CONTENT_PERMANENTLY_DELETED',
  USER_PROFILE_UPDATED = 'USER_PROFILE_UPDATED',
}

export interface AuditLog {
  id: number;
  timestamp: string;
  action: AuditLogAction;
  details: string;
}